# Generated by Django 3.1.3 on 2020-11-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('camera_index', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Motion',
                'verbose_name_plural': 'Motions',
            },
        ),
    ]
